// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingMachineApp.Data;

#nullable disable

namespace VendingMachineApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.MaintenanceLog", b =>
                {
                    b.Property<int>("MaintenanceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceLogId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceLogId");

                    b.HasIndex("MachineId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("MaintenanceLogs");

                    b.HasData(
                        new
                        {
                            MaintenanceLogId = 1,
                            Cost = 120m,
                            Description = "Zamjena motora",
                            MachineId = 1,
                            MaintenanceDate = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Završeno",
                            TechnicianId = 1
                        },
                        new
                        {
                            MaintenanceLogId = 2,
                            Cost = 30m,
                            Description = "Čišćenje aparata",
                            MachineId = 2,
                            MaintenanceDate = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Završeno",
                            TechnicianId = 2
                        },
                        new
                        {
                            MaintenanceLogId = 3,
                            Cost = 80m,
                            Description = "Popravka displeja",
                            MachineId = 1,
                            MaintenanceDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "U toku",
                            TechnicianId = 1
                        },
                        new
                        {
                            MaintenanceLogId = 4,
                            Cost = 50m,
                            Description = "Zamjena brave",
                            MachineId = 3,
                            MaintenanceDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Završeno",
                            TechnicianId = 3
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            DeliveryDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            SupplierId = 1,
                            TotalAmount = 100.0m
                        },
                        new
                        {
                            OrderId = 2,
                            DeliveryDate = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            SupplierId = 2,
                            TotalAmount = 150.0m
                        },
                        new
                        {
                            OrderId = 3,
                            DeliveryDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            SupplierId = 3,
                            TotalAmount = 200.0m
                        },
                        new
                        {
                            OrderId = 4,
                            OrderDate = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            SupplierId = 4,
                            TotalAmount = 80.0m
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 10,
                            SubTotal = 25.0m,
                            UnitPrice = 2.5m
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 5,
                            SubTotal = 7.5m,
                            UnitPrice = 1.5m
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 3,
                            ProductId = 2,
                            Quantity = 8,
                            SubTotal = 16.0m,
                            UnitPrice = 2.0m
                        },
                        new
                        {
                            OrderItemId = 4,
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 3,
                            SubTotal = 10.5m,
                            UnitPrice = 3.5m
                        },
                        new
                        {
                            OrderItemId = 5,
                            OrderId = 2,
                            ProductId = 10,
                            Quantity = 6,
                            SubTotal = 13.2m,
                            UnitPrice = 2.2m
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReorderThreshold")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = 1,
                            Description = "Gazirani napitak",
                            ExpirationDate = new DateTime(2027, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Coca-Cola",
                            Price = 2.5m,
                            ReorderThreshold = 10,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            Category = 1,
                            Description = "Gazirani napitak",
                            ExpirationDate = new DateTime(2028, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fanta",
                            Price = 2.4m,
                            ReorderThreshold = 10,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            Category = 1,
                            Description = "Gazirani napitak",
                            ExpirationDate = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sprite",
                            Price = 2.4m,
                            ReorderThreshold = 10,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Category = 2,
                            Description = "Čokoladica",
                            ExpirationDate = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snickers",
                            Price = 1.5m,
                            ReorderThreshold = 10,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            Category = 2,
                            Description = "Čokoladica",
                            ExpirationDate = new DateTime(2027, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mars",
                            Price = 1.6m,
                            ReorderThreshold = 10,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            Category = 2,
                            Description = "Snack croissant",
                            ExpirationDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "7Days Croissant",
                            Price = 1.8m,
                            ReorderThreshold = 7,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            Category = 5,
                            Description = "Krompir čips",
                            ExpirationDate = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hrusty čips classic",
                            Price = 2.0m,
                            ReorderThreshold = 8,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            Category = 5,
                            Description = "Tortilla čips",
                            ExpirationDate = new DateTime(2026, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doritos",
                            Price = 2.2m,
                            ReorderThreshold = 8,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 6,
                            Category = 6,
                            Description = "Sendvič",
                            ExpirationDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sandwich",
                            Price = 3.5m,
                            ReorderThreshold = 3,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 7,
                            Category = 4,
                            Description = "Muesli bar",
                            ExpirationDate = new DateTime(2026, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2025, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Muesli Bar",
                            Price = 1.2m,
                            ReorderThreshold = 6,
                            SupplierId = 4
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.ProductSlot", b =>
                {
                    b.Property<int>("ProductSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductSlotId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRestockedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.HasKey("ProductSlotId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSlots");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Radnička cesta 1, 10000 Zagreb",
                            ContactPerson = "Ana Kola",
                            Email = "info@cocacola.hr",
                            Name = "Coca-Cola Bottling Hrvatska",
                            PhoneNumber = "0800-123-456",
                            RegistrationDate = new DateTime(2012, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Savska cesta 32, 10000 Zagreb",
                            ContactPerson = "Marko Mars",
                            Email = "info@mars.com",
                            Name = "Mars Wrigley Hrvatska",
                            PhoneNumber = "0800-555-333",
                            RegistrationDate = new DateTime(2018, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Hrusty Lane 7, 10000 Zagreb",
                            ContactPerson = "Hrvoje Čips",
                            Email = "info@hrusty.hr",
                            Name = "Hrusty d.o.o.",
                            PhoneNumber = "0800-444-555",
                            RegistrationDate = new DateTime(2013, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "Ulica Snackova 15, 21000 Split",
                            ContactPerson = "Petra Grickalica",
                            Email = "info@snackgo.hr",
                            Name = "Snack&Go d.o.o.",
                            PhoneNumber = "0800-777-888",
                            RegistrationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Email = "ivan@firma.com",
                            HireDate = new DateTime(2019, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "LIC001",
                            Name = "Ivan Ivić",
                            PhoneNumber = "061-111-111"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Email = "ana@firma.com",
                            HireDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "LIC002",
                            Name = "Ana Aničić",
                            PhoneNumber = "062-222-222"
                        },
                        new
                        {
                            TechnicianId = 3,
                            Email = "marko@firma.com",
                            HireDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LicenseNumber = "LIC003",
                            Name = "Marko Marković",
                            PhoneNumber = "063-333-333"
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductNumberEntered")
                        .HasColumnType("int");

                    b.Property<int>("QuantityDispensed")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AmountPaid = 2.5m,
                            MachineId = 1,
                            ProductId = 1,
                            ProductNumberEntered = 1,
                            QuantityDispensed = 1,
                            Status = 2,
                            TotalPrice = 2.5m,
                            TransactionDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 2,
                            AmountPaid = 1.5m,
                            MachineId = 2,
                            ProductId = 3,
                            ProductNumberEntered = 2,
                            QuantityDispensed = 0,
                            Status = 3,
                            TotalPrice = 1.5m,
                            TransactionDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 3,
                            AmountPaid = 2.0m,
                            MachineId = 1,
                            ProductId = 2,
                            ProductNumberEntered = 3,
                            QuantityDispensed = 1,
                            Status = 2,
                            TotalPrice = 2.0m,
                            TransactionDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 4,
                            AmountPaid = 3.5m,
                            MachineId = 3,
                            ProductId = 6,
                            ProductNumberEntered = 4,
                            QuantityDispensed = 1,
                            Status = 2,
                            TotalPrice = 3.5m,
                            TransactionDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.VendingMachine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManufacturedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MachineId");

                    b.ToTable("VendingMachines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            Address = "Ilica 15, Zagreb",
                            Capacity = 50,
                            CurrentBalance = 100.0m,
                            LastMaintenanceDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineNumber = 101,
                            ManufacturedDate = new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            MachineId = 2,
                            Address = "Avenija Dubrovnik 10, Zagreb",
                            Capacity = 60,
                            CurrentBalance = 200.0m,
                            LastMaintenanceDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineNumber = 102,
                            ManufacturedDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            MachineId = 3,
                            Address = "Savska cesta 50, Zagreb",
                            Capacity = 40,
                            CurrentBalance = 50.0m,
                            LastMaintenanceDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineNumber = 103,
                            ManufacturedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3
                        },
                        new
                        {
                            MachineId = 4,
                            Address = "Korzo 5, Rijeka",
                            Capacity = 70,
                            CurrentBalance = 300.0m,
                            LastMaintenanceDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineNumber = 104,
                            ManufacturedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            MachineId = 5,
                            Address = "Trg bana Jelačića 1, Zagreb",
                            Capacity = 55,
                            CurrentBalance = 0.0m,
                            LastMaintenanceDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineNumber = 105,
                            ManufacturedDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 4
                        },
                        new
                        {
                            MachineId = 6,
                            Address = "Riva 8, Split",
                            Capacity = 80,
                            CurrentBalance = 500.0m,
                            LastMaintenanceDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MachineNumber = 106,
                            ManufacturedDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendingMachineApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.VendingMachine", "VendingMachine")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendingMachineApp.Data.Entities.Technician", "Technician")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("VendingMachine");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Order", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.Supplier", "Supplier")
                        .WithMany("Orders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendingMachineApp.Data.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Product", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.ProductSlot", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.VendingMachine", "VendingMachine")
                        .WithMany("ProductSlots")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendingMachineApp.Data.Entities.Product", "Product")
                        .WithMany("ProductSlots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("VendingMachine");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Transaction", b =>
                {
                    b.HasOne("VendingMachineApp.Data.Entities.VendingMachine", "VendingMachine")
                        .WithMany("Transactions")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendingMachineApp.Data.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("VendingMachine");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductSlots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.Technician", b =>
                {
                    b.Navigation("MaintenanceLogs");
                });

            modelBuilder.Entity("VendingMachineApp.Data.Entities.VendingMachine", b =>
                {
                    b.Navigation("MaintenanceLogs");

                    b.Navigation("ProductSlots");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
